#!/bin/bash
# iterate through all the files in directory

for file in /root/test/*
do

   if [ -d "$file" ]
   then
      echo "$file is a directory"
   elif [ -f $file ]
   then
      echo "$file is a file"
   fi
done
