#!/bin/bash
# using the case command

case $USER in
rich | barbara)
   echo "Welcome, $USER"
   echo "Please enjoy you visit";;
testing)
   echo "Special testing account";;
jessica)
   echo "Do not forget to log off when you are done";;
*)
   echo "Sorry, you are not allowed here";
esac
