#!/bin/bash
# testing file dates

if [ ./test19 -nt ./test18 ]
then
   echo "The test19 file is newer than test18"
else
   echo "The test18 file is newer than test19"
fi

if [ ./test17 -ot ./test19 ]
then
   echo "The test17 file is older than the test19"
else
   echo "The test19 file is older than test17"
fi
