#!/bin/bash
# trying to access script parameters

function func7 {
   echo $[ $1 * $2 ] 
}

if [ $# -eq 2 ]
then
   value=`func7 $1 $2`
   echo "The result is $value"
else
   echo "Usage: badtest1 a b"
fi
